// Code generated by mtribes. DO NOT EDIT.

/* tslint:disable */
import { Fallbacks } from '@mtribes/client-browser';

export const fallbacks: Fallbacks = {
  v: 17727,
  json: '{"3q6rn6p":{"on":true,"sid":"ojBovxy","v":29989,"data":"{\\"1\\":\\"https://images.unsplash.com/photo-1484627147104-f5197bcd6651?ixlib=rb-1.2.1\\u0026amp;q=80\\u0026amp;fm=jpg\\u0026amp;crop=entropy\\u0026amp;cs=tinysrgb\\u0026amp;dl=denys-nevozhai-z0nVqfrOqWA-unsplash.jpg\\u0026amp;w=800\\"}","pid":"yxE8Q2R"},"8x6DeEy":{"on":true,"sid":"9RDRWkq","v":27366,"data":"{\\"1\\":{\\"opacity\\":1.000,\\"value\\":\\"#209\\"},\\"2\\":{\\"opacity\\":1.000,\\"value\\":\\"#2363ae\\"}}"},"nLK0ZEJ":{"on":true,"sid":"2Po3pBb","v":38251,"data":"{\\"1\\":\\"\\"}","pid":"yxE8Q2R"},"yxE8Q2R":{"on":true,"sid":"4pLMZlk","v":15790,"se":[{"id":"3q6rn6p","et":"VGd1POB"},{"id":"nLK0ZEJ","et":"NW0bo31"}]}}'
};
