// Code generated by mtribes. DO NOT EDIT.

/* tslint:disable */
import {
	Client,
	Broker,
	Signal as SignalAlias,
	SessionEvent as SessionEventAlias,
	ChangeEvent as ChangeEventAlias,
	ColorProperty as ColorPropertyAlias
} from '@mtribes/client-browser';
import { fallbacks } from './fallbacks';
import HomepageCollection from './collection/homepageCollection';

export {
	Client,
	Session,
	SessionStatus,
	ChangeEventType,
	Experience,
	Section
} from '@mtribes/client-browser';

export type Signal<SessionEvent> = SignalAlias<SessionEvent>;
export type SessionEvent = SessionEventAlias;
export type ChangeEvent = ChangeEventAlias;
export type ColorProperty = ColorPropertyAlias;

const broker = new Broker();
export const client = new Client('6ce409e6860440b18f581233cd41b4ca', fallbacks, broker);
export const session = client.session;

export const collections: Collections = {
	homepage: new HomepageCollection('wN23m6l', [
	'8x6DeEy',
	'yxE8Q2R'
	], broker),
};

export interface Collections {
	homepage: HomepageCollection;
}