// Code generated by mtribes. DO NOT EDIT.

/* tslint:disable */
import { Collection, Broker } from '@mtribes/client-browser';

import HomepageBodySection from '../section/homepageBodySection';
import HeaderExperience from '../experience/headerExperience';

export default class HomepageCollection extends Collection {
	
	readonly header: HeaderExperience;
	readonly body: HomepageBodySection;

	constructor(id: string, childIds: string[], broker: Broker) {
		super(id, broker, {
			id: '5Lb7ZGo',
			t: 'c'
		});
		this.header = new HeaderExperience(childIds[0], id, broker);
		this.body = new HomepageBodySection(childIds[1], id, broker);
	}
}
