// Code generated by mtribes. DO NOT EDIT.

/* tslint:disable */
import { Experience, Broker } from '@mtribes/client-browser';

export interface BannerExperienceData {
	label?: string;
}

export default class BannerExperience extends Experience<BannerExperienceData> {
	/**
	 * The kind of Experience in string form.
	 */
	readonly kind = 'BannerExperience';

	constructor(id: string, parentId: string, broker: Broker) {
		super(id, parentId, broker, {
			id: 'NW0bo31',
			t: 'e',
			dataAlias: {
				'1': 'label'
			}
		});
	}
}