// Code generated by mtribes. DO NOT EDIT.

/* tslint:disable */
import { Section, Broker } from '@mtribes/client-browser';

import HeroExperience from '../experience/heroExperience';
import BannerExperience from '../experience/bannerExperience';

export class HomepageBodySectionSupported {
	readonly Hero = 'HeroExperience';
	readonly Banner = 'BannerExperience';
}

export type HomepageBodySectionSupportedTypes = HeroExperience|BannerExperience;

export default class HomepageBodySection extends Section<HomepageBodySectionSupported, HomepageBodySectionSupportedTypes> {
	// Type alias's for easy switching of supported Section Experience types
	readonly supported = new HomepageBodySectionSupported();

	constructor(id: string, parentId: string, broker: Broker) {
		super(id, parentId, broker, {
			id: '5ozXdgW',
			t: 's'
		}, {
			'VGd1POB': HeroExperience,
			'NW0bo31': BannerExperience
		});
	}
}
